-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgKUAvFOjhEX91uGTX
UO1V9xTM7fCuIH29nZZEfVF+rGigCgYIKoZIzj0DAQehRANCAASrIZLYHz2wpMUk
PxxoEvGy4EHJdyWEmqPfVMqAkcfAS1/cMQ2YQQhmS5zqasB3CAOHyk30mlVWocRO
7ngQzPYq
-----END PRIVATE KEY-----